const GET_CURRENCY_REQUEST = 'GET_CURRENCY_REQUEST';
const GET_CURRENCY_SUCCESS = 'GET_CURRENCY_SUCCESS';
const GET_CURRENCY_FAILED = 'GET_CURRENCY_FAILED';

export { GET_CURRENCY_REQUEST, GET_CURRENCY_SUCCESS, GET_CURRENCY_FAILED };
